baseurl = "https://example.com/"
title = "Site Title"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
pygmentsCodefences = true
pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[params]
    author = "Your Name"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    discription = """
        Please write anything here.
        Profiles, backgrounds, favorite things etc.
    """
    publicationYear = "2018"
    listPageDateFormat = "January, 2006"   # See https://gohugo.io/functions/format/
    singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    name = "Blog"
    url = "/blog/"

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/username"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/username"

[[menu.main]]
    name = "Email"
    url = "mailto:username@example.com"

