baseurl = "https://example.com/"
title = "Site Title"
theme = "pulp"
canonifyurls = true
pygmentsCodefences = true
pygmentsUseClasses = true

[params]
    author = "Kazuki Koide"
    avatar = "avatar.jpg"
    discription = """
        I’m a Web Engeneer working in Tokyo.
        I’d like to make products that take people to the future.
        Have a look at some of my blog posts.
        If you have a comment, please feel free to
        follow on Twitter or contact by Email.
    """
    publicationYear = "2018"
    custom_css = ["css/custom.css"]
    custom_js = ["js/custom.js"]

[[params.nav]]
    name = "Blog"
    url = "/blog/"

[[params.nav]]
    name = "Twitter"
    url = "https://twitter.com/username"

[[params.nav]]
    name = "GitHub"
    url = "https://github.com/username"

[[params.nav]]
    name = "Email"
    url = "mailto:username@example.com"

